"""crear tabla rutinas

Revision ID: 08e1bc23cf61
Revises: 4615f28fff46
Create Date: 2026-07-17 19:05:34.632287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e1bc23cf61'
down_revision = '4615f28fff46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rutinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rutinas_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutinas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rutinas_usuario_id'))

    op.drop_table('rutinas')
    # ### end Alembic commands ###
