"""crear tabla entrenamientos

Revision ID: 2840070d9c1b
Revises: 979c49f9eda1
Create Date: 2026-07-17 23:24:05.981153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2840070d9c1b'
down_revision = '979c49f9eda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrenamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.Column('nombre_rutina', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entrenamientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrenamientos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrenamientos_rutina_id'), ['rutina_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrenamientos_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenamientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrenamientos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_entrenamientos_rutina_id'))
        batch_op.drop_index(batch_op.f('ix_entrenamientos_fecha'))

    op.drop_table('entrenamientos')
    # ### end Alembic commands ###
