"""crear tabla recordatorios

Revision ID: 3f7bc40f7e76
Revises: cf0a3205289f
Create Date: 2026-07-18 02:03:37.107227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7bc40f7e76'
down_revision = 'cf0a3205289f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora', sa.Integer(), nullable=False),
    sa.Column('minuto', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recordatorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recordatorios_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordatorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recordatorios_usuario_id'))

    op.drop_table('recordatorios')
    # ### end Alembic commands ###
