"""crear tabla ejercicios

Revision ID: 979c49f9eda1
Revises: 08e1bc23cf61
Create Date: 2026-07-17 21:59:23.517702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979c49f9eda1'
down_revision = '08e1bc23cf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ejercicios_rutina_id'), ['rutina_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejercicios_rutina_id'))

    op.drop_table('ejercicios')
    # ### end Alembic commands ###
