"""crear tabla pesos

Revision ID: cf0a3205289f
Revises: 2840070d9c1b
Create Date: 2026-07-18 00:47:31.913442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0a3205289f'
down_revision = '2840070d9c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pesos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pesos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_pesos_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pesos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pesos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_pesos_fecha'))

    op.drop_table('pesos')
    # ### end Alembic commands ###
